apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-deployment
  labels:
    app: color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: color
        image: aprabhat/color:green
        ports:
        - containerPort: 3000
